version: "3"

volumes:
    code_breaking-postgres-volume:
    code_breaking-postgres-teste-volume:
    code_breaking-redis-volume:


networks:
    laranet_code_breaking:
        driver: bridge

services:
    ######## APP ########
    code_breaking:
        build:
            context: ..
            dockerfile: .docker/Dockerfile
        command: "/usr/local/bin/start"
        working_dir: /var/www/app
        volumes:
            - ../:/var/www/app:cached
        ports:
            - 8081:8080
        depends_on:
            - code_breaking-postgres
            - code_breaking-postgres-teste
            - code_breaking-redis
        networks:
            - laranet_code_breaking

    ######## REDIS ########
    code_breaking-redis:
        image: redis:7.0.5
        volumes:
            - code_breaking-redis-volume:/data
        ports:
            - 6380:6379
        networks:
            - laranet_code_breaking

    ######## POSTGRES ########
    code_breaking-postgres:
        image: postgres:14.6
        environment:
            - POSTGRES_DB=code_breaking-db
            - POSTGRES_USER=code_breaking
            - POSTGRES_PASSWORD=code_breaking
        volumes:
            - code_breaking-postgres-volume:/var/lib/postgresql/data
        ports:
            - 5433:5432
        networks:
            - laranet_code_breaking

    ######## POSTGRES (TESTE AUTOMATIZADO) ########
    code_breaking-postgres-teste:
        image: postgres:14.6
        environment:
            - POSTGRES_DB=code_breaking-db
            - POSTGRES_USER=code_breaking
            - POSTGRES_PASSWORD=code_breaking
        volumes:
            - code_breaking-postgres-teste-volume:/var/lib/postgresql/data
        ports:
            - 54178:5432
        networks:
            - laranet_code_breaking
